Fix: Correct database import destructuring in utilities and controllers
- Fixed utils/statistics.js: Change 'const db = require' to 'const { db } = require'
- Fixed utils/adminLogger.js: Change 'const db = require' to 'const { db } = require'
- Fixed utils/ocrQuota.js: Change 'const db = require' to 'const { db } = require'
- Fixed controllers/paymentsController.js: Change 'const db = require' to 'const { db } = require'

This resolves the 'TypeError: db.query is not a function' error that was occurring
because the database module exports { db, testDatabase } as an object, so it needs
to be destructured when imported.